# Generated by Django 6.0.2 on 2026-02-22 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement', '0002_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='thread',
            field=models.ForeignKey(blank=True, help_text='The thread this statement was generated in', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='statement.thread'),
        ),
    ]
